---
# tasks file for wordpress
- name: "activation du module rewrite"
  command: /usr/sbin/a2enmod rewrite

- name: "création du fichier de configuration"
  copy:
    src: wordpress.conf
    dest: /etc/apache2/sites-available/wordpress.conf

- name: "activation de l'hote virtuel"
  command: /usr/sbin/a2ensite wordpress

- name: "rechargement de la configuration apache"
  service: 
    name: apache2
    state: reloaded
    enabled: yes

- name: "installation de unzip"
  apt:
    name: unzip
    state: present

- name: "téléchargement de la dernière version de wordpress"
  unarchive:
    src: https://fr.wordpress.org/wordpress-latest-fr_FR.zip
    dest: /var/www/html
    remote_src: yes
    
- name: "création de la base de données wordpress"
  command: /usr/bin/mysqladmin create "{{wordpress_db}}"

- name: "création d'un utilisateur"
  command: /usr/bin/mysql -e "CREATE USER 'wordpress' IDENTIFIED BY 'wordpress'"

- name: "connexion à la base"
  command: /usr/bin/mysql -e "USE wordpress"

- name: "ajout de privilège"
  command: /usr/bin/mysql -e "GRANT ALL ON wordpress.* TO 'wordpress'"
    
- name: "copie du fichier de configuration wordpress"
  copy:
    src: wp-config.php
    dest: /var/www/html/wordpress/wp-config.php
