---
# tasks file for apache
#- name: "mise à jour apt"
#  apt:
#    update_cache: yes

- name: "installation apache"
  apt:
    name: apache2
    state: latest
    
- name: "activation"
  service:
    name: apache2
    state: started
    enabled: yes
