---
# tasks file for apache

#- name: "mise a jour depot"
#  command: /usr/bin/apt-get update -m --ignore-missing

- name: "installation apache"
  apt:
    name: apache2
    state: latest
    
- name: "activation"
  service:
    name: apache2
    state: started
    enabled: yes
