---
# tasks file for apache
#- name: "mise à jour apt"
#  command: /usr/bin/apt update

- name: "installation apache"
  apt:
    name: apache2
    state: latest
    
- name: "activation"
  service:
    name: apache2
    state: started
    enabled: yes
