---
# tasks file for mysql
  - name: "installation du paquet mysql-server"
    apt:
      name: mysql-server
      state: present

  - name: "installation du paquet python3-mysql.connector"
    apt:
      name: python3-mysql.connector
      state: present

