---
# tasks file for mysql
  - name: "installation du paquet mysql-server"
    apt:
      name: mysql-server
      state: present
      
  - name: "redémarrage du service"
    service:
      name: mysql
      state: restarted

